config/routes.rb
Rails.application.routes.draw do
  get 'homes/index'
  devise_for :users, controllers: {
    omniauth_callbacks: "omniauth_callbacks"
  }
  
  get 'hello/index' => 'hello#index'

  resources :users, only: [:show]
  
  get'blogs/index'
  resources :blogs
  
  resources :posts do
    resources :likes, only: [:create, :destroy]
  end

  post 'callback' => 'line_bot#callback'

  root 'hello#index'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :validatable,
        :omniauthable, omniauth_providers: %i[line]

        has_many :blogs
        validates :name, presence: true
        validates :profile, length: { maximum: 200 }
        mount_uploader :image, ImageUploader

        def social_profile(provider)
          social_profiles.select { |sp| sp.provider == provider.to_s }.first
        end
      
        def set_values(omniauth)
          return if provider.to_s != omniauth["provider"].to_s || uid != omniauth["uid"]
          credentials = omniauth["credentials"]
          info = omniauth["info"]
      
          access_token = credentials["refresh_token"]
          access_secret = credentials["secret"]
          credentials = credentials.to_json
          name = info["name"]
          # self.set_values_by_raw_info(omniauth['extra']['raw_info'])
        end
      
        def set_values_by_raw_info(raw_info)
          self.raw_info = raw_info.to_json
          self.save!
        end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
    protect_from_forgery

    
    protected
    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :image])
        devise_parameter_sanitizer.permit(:account_update, keys: [:name, :profile, :image])
    end

end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController

    before_action :authenticate_user!, :set_beginning_of_week

    def index
        @blogs = Blog.all
    end
    
    def new
        @blog = Blog.new
    end
    
    def show
        @blog = Blog.find(params[:id])
    end
    
    def create

        blog = Blog.new(blog_parameter)

        blog.user_id = current_user.id

        blog.user_uid = current_user.uid

        if blog.save
            redirect_to  user_path(current_user.id)
        else
            redirect_to :action => "new"
        end
    end
    
    def destroy
        @blog = Blog.find(params[:id])
        @blog.destroy
        @blog.destroy
            redirect_to blogs_path, notice:"削除しました"
    end
    
    def edit
        @blog = Blog.find(params[:id])
    end
    
    def update
        @blog = Blog.find(params[:id])
        if @blog.update(blog_parameter)
            redirect_to blogs_path, notice: "編集しました"
        else
            render 'edit'
        end
    end
    
    private
    
    def blog_parameter
        params.require(:blog).permit(:title, :content, :start_time, :release)
    end

    def set_beginning_of_week
        Date.beginning_of_week = :sunday
    end
end

app/controllers/hello_controller.rb
class HelloController < ApplicationController
    def index
        
    end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
end

app/controllers/line_bot_controller.rb
class LineBotController < ApplicationController
    def callback
        body = request.body.read
        events = client.parse_events_from(body)
        events.each do |event|
            case event
            when Line::Bot::Event::Message
                case event.type
                when Line::Bot::Event::MessageType::Text
                    message = {
                        type: "text",
                        text: event.message["text"]
                    }
                    client.reply_message(event['replyToken'], message)
                end
            end
        end
    end
    
    private
    
    def client
        @client ||= Line::Bot::Client.new { |config|
            config.channel_secret = ENV["LINE_CHANNEL_SECRET"]
            config.channel_token = ENV["LINE_CHANNEL_TOKEN"]
        }
    end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
    def line; ; end

    def line; basic_action end

    private
    def basic_action
        @omniauth = request.env["omniauth.auth"]
        if @omniauth.present?
            @profile = User.find_or_initialize_by(provider: @omniauth["provider"], uid: @omniauth["uid"])
            if @profile.email.blank?
                email = @omniauth["info"]["email"] ? @omniauth["info"]["email"] : "#{@omniauth["uid"]}-#{@omniauth["provider"]}@example.com"
                @profile = current_user || User.create!(provider: @omniauth["provider"], uid: @omniauth["uid"], email: email, name: @omniauth["info"]["name"], password: Devise.friendly_token[0, 20])
            end
            @profile.set_values(@omniauth)
            sign_in(:user, @profile)
        end
        flash[:notice] = "ログインしました"
        redirect_to root_path
    end

    def fake_email(uid, provider)
        "#{auth.uid}-#{auth.provider}@example.com"
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    before_action :set_beginning_of_week
    
    def show
        @user = User.find(params[:id])    
    end

    private

    def set_beginning_of_week
        Date.beginning_of_week = :sunday
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/hello_helper.rb
module HelloHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/line_bot_helper.rb
module LineBotHelper
end

app/helpers/omniauth_callbacks_helper.rb
module OmniauthCallbacksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blogs/edit.html.erb
<%= form_with(model: @blog, local: true) do |form| %>

<br>
<br>
    <div class="title">
        <%= form.label :title %>
        <%= form.text_field :title %>
    </div>

    <div class="time">
        <%= form.label :deadline %>
        <%= form.datetime_select :deadline %>
    </div>

    <div class="content">
        <%= form.label :content %>
        <%= form.text_field :content %>
    </div>

    
    <%= form.label :release, "Status" %><br>
    <%= form.select :release,[["Public", "Publi"],["Private", "Private"]], include_blank: "選択してください" %><br>

    <div class="submit">
        <%= form.submit %>
    </div>

    
<% end %>

app/views/blogs/index.html.erb
<p id="notice"><%= notice %></p>

<div class="momo">

<h3>Everyone's Task</h3>

<div class="box" align="right">
    <%= button_to 'Logout', destroy_user_session_path, method: :delete %>
</div>
<br>

<%= link_to 'New Task', new_blog_path %>
    <i class="fa-regular fa-calendar-plus"></i>
<br>
<br>
<%= link_to 'MyPage', user_path(current_user.id) %>
    <i class="fa-regular fa-user"></i>
<br>
<br>
<br>

<%= month_calendar events: @blogs do |date, blogs| %>
<%= date.day %>


<%# blogs.each do |blog| %>
    <div>
        <%#= link_to blog.title, blog %>
    </div>

<div class="release">
        <ul>
            <% blogs.each do |t| %>
                <% if t.release == "Public" %> 
                    <div class="blog">
                        <li><%= t.title %></li>
                    </div>
                <% end %>
            <% end %>
        </ul>
    </div>
    <div class="unrelease">
        <ul>
            <% blogs.each do |t| %>
                <% if t.release == "Private" %> 
                    <div class="blog">
                        <li><%= t.title %></li>
                    </div>
                <% end %>
            <% end %>
        </ul>
    </div>
</div>

<%# end %>

<% end %>
</div>

app/views/blogs/new.html.erb
<%= form_with(model: @blog, local: true) do |form| %>
<br>
<br>
    <div class="post-container">
        <div class="title">
            <%= form.label :title %>
            <%= form.text_field :title %>
        </div>
<br>
        <div class="content">
            <%= form.label :content %>
            <%= form.text_field :content %>
        </div>
<br>
        <div class="time">
            <%= form.label :deadline %>
            <%= form.datetime_select :deadline %>
        </div>
<br>
        <%= form.label :release, "Status" %><br>
        <%= form.select :release,[["Public", "Public"],["Private", "Private"]], include_blank: "" %><br>
<br>      
        <div class="submit">
            <%= form.submit %>
        </div>
    </div>
<% end %>

app/views/blogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
    <strong>タイトル</strong>
        <%= @blog.title %>
</p>

<p>
    <strong>時間</strong>
        <%= @blog.start_time.strftime("%H:%M") %>
</p>

<p>
    <strong>内容</strong>
        <%= @blog.content %>
</p>



<%= link_to "Done", blog_path(@blog.id), method: :delete %>
    <i class="fa-regular fa-circle-check"></i>
<%= link_to 'Edit', edit_blog_path(@blog) %> 
    <i class="fa-regular fa-pen-to-square"></i>
<%= link_to 'Back', blogs_path %>
    <i class="fa-regular fa-share-from-square"></i>

app/views/homes/index.html.erb
<h1>Homes#index</h1>
<p>Find me in app/views/homes/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.14.0/css/all.css">
    <script src="https://kit.fontawesome.com/b7d1e3bceb.js" crossorigin="anonymous"></script>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <header>
      <div class="header-list">
      <ul>  
        <li><%= link_to "Login", blogs_path %></li>
        <li><%= link_to "Home", blogs_path %></li>
      </ul>
      </div>
    </header>
    <main>
      <%= yield %>
    </main>  
    <footer>
      <p>Copyright © momoko All Rights Reserved.</p>
    </footer>
      <div>
          <p class="timechange-sample"></p>
          <script type="text/javascript">
            $(document).ready(function(){
            var day = new Date();
            var hour = day.getHours();
      
            if( hour <= 1 )	{	
            $('.timechange-sample').css('background-image', 'url(https://images.unsplash.com/photo-1488866022504-f2584929ca5f?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTJ8fG5pZ2h0fGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=700&q=60)');
            }
            else if( hour <= 7 )	{	
              $('.timechange-sample').css('background-image', 'url(https://images.unsplash.com/photo-1500382017468-9049fed747ef?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NHx8c3VucmlzZXxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=700&q=60)');
            }
            else if( hour <= 11 ) {
              $('.timechange-sample').css('background-image', 'url(https://images.unsplash.com/photo-1465488867967-ffb57e7f0a89?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHx2aXN1YWwtc2VhcmNofDF8fHxlbnwwfHx8fA%3D%3D&auto=format&fit=crop&w=800&q=60)');
            }
            else if( hour <= 16 ) {	
              $('.timechange-sample').css('background-image', 'url(https://images.unsplash.com/photo-1505533542167-8c89838bb19e?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHx2aXN1YWwtc2VhcmNofDF8fHxlbnwwfHx8fA%3D%3D&auto=format&fit=crop&w=800&q=60)');
            }
            else if( hour <= 20 ) {
              $('.timechange-sample').css('background-image', 'url(https://images.unsplash.com/photo-1519414442781-fbd745c5b497?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHx2aXN1YWwtc2VhcmNofDF8fHxlbnwwfHx8fA%3D%3D&auto=format&fit=crop&w=700&q=60)');
            }
            else if( hour <= 24 ) {
            $('.timechange-sample').css('background-image','url(https://images.unsplash.com/photo-1582702877108-546b84049d77?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHx2aXN1YWwtc2VhcmNofDV8fHxlbnwwfHx8fA%3D%3D&auto=format&fit=crop&w=700&q=60)');
            }
            });
          </script>
      </div>
      <style>
        .timechange-sample{
          position: absolute;
          top: 100px;
          bottom: 0px;
          z-index: -100;
          width: 100%;
          height: 1000px;
          text-align: center;
          padding: 120px 5px;
          background-repeat: no-repeat;
          background-size:100% auto;
          opacity: 0.7 ;
          }
      </style>
  </body>
</html>

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th class="weekcolor"><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <%= content_tag :tr, class: calendar.tr_classes_for(week) do %>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_week_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <% if calendar.number_of_weeks == 1 %>
      <span class="calendar-title"><%= t('simple_calendar.week', default: 'Week') %> <%= calendar.week_number %></span>
    <% else %>
      <span class="calendar-title"><%= t('simple_calendar.week', default: 'Week') %> <%= calendar.week_number %> - <%= calendar.end_week %></span>
    <% end %>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<h1>MyPage</h1>

<% if @user.image? %>                                                              
    <%= image_tag @user.image.url, class: "rounded-circle", size: "150x150" %>
<% else %>
    <%= image_tag "default.jpg", size: "150x150" %>
<% end %>

<p>Name : <%= @user.name %></p>
<br>
<p>Email : <%= @user.email %></p>
<br>
<p>Profile : <%= @user.profile %></p>
<br>

<% if current_user.id == @user.id %>
    <%= link_to "Edit me", edit_user_registration_path %>
<% end %>
<br>
<br>

<%= link_to 'New Task', new_blog_path %>

<p id="notice"><%= notice %></p>


<%= month_calendar events: @user.blogs do |date, post| %>
    <%= date.day %>

    <% post.each do |post| %>
    <div>
        <%= link_to post.title, post %>
        <%= post.start_time.strftime("%H:%M") %>
    </div>
    <% end %>
<% end %>



<script>
    function GethashID (hashIDName){
        if(hashIDName){
            $('.tab li').find('a').each(function() {
                var idName = $(this).attr('href');
                if(idName == hashIDName){ 
                    var parentElm = $(this).parent();
                    $('.tab li').removeClass("active");
                    $(parentElm).addClass("active");
                    $(".area").removeClass("is-active");
                    $(hashIDName).addClass("is-active"); 
                }
            });   
        }
    }

    $('.tab a').on('click', function() {
        var idName = $(this).attr('href');
        GethashID (idName);
        return false;
    });

    $(window).on('load', function () {
            $('.tab li:first-of-type').addClass("active");
            $('.area:first-of-type').addClass("is-active");
        var hashName = location.hash;
        GethashID (hashName);
    });
</script>

<br>
<br>
<br>